name: CI and CD
on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
          token: ${{ secrets.GH_REPO_TOKEN }}
      - name: Set-up Node
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - run: yarn install
      - run: yarn build        
